image: docker:19.03.11

tests:
    services:
        - docker:19.03.11-dind
    script:
        - docker build -t exchange:dev exchange-rate/
        - docker run exchange:dev bundle exec ruby test/run_tests.rb
