# Use this file to list any gems that need to be included for your solution to run
# https://bundler.io/
source "https://rubygems.org"

gem "test-unit"


# Ruby 2.6.x requires the `irb` gem to be in the Gemfile
gem "irb" if defined?(RUBY_VERSION) && RUBY_VERSION.to_f >= 2.6

gem "mocha", "~> 1.11"

gem "yard", "~> 0.9.35"

gem "yard-tomdoc", "~> 0.7.1"
